export const CONFIG = {
  VIEW_PASSWORD_HASH: import.meta.env.VITE_VIEW_PASSWORD_HASH || '__VIEW_PASSWORD_HASH__',
  EDITOR_TOKEN_HASH: import.meta.env.VITE_EDITOR_TOKEN_HASH || '__EDITOR_TOKEN_HASH__',
  GIST_ID: '84595e25d454041cf0fe03d2975961dc',
}
